services:
  database:
    image: mariadb:11.4
    container_name: homa-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: emili123
      MARIADB_DATABASE: homa_avanzada_db
      MARIADB_USER: root
      MARIADB_PASSWORD: homapass
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: homa-backend:1.0
    container_name: homa-backend
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://homa-mariadb:3306/homa_avanzada_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: emili123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
    ports:
      - "8080:8080"

volumes:
  mysql_data:
